name: Docker-GCP-CI-CD
on:
  push:

jobs:
  docker-release:
    name: Build and Deploy FastAPI Container to Google App Engine
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
         - uses:actions/checkout@v4
         - uses:google-github-actions/auth@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/415226216547/locations/global/workloadIdentityPools/my-pool/providers/github-01
          service_account: githubacc-274@bright-airport-419808.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: me-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
             me-west1-docker.pkg.dev/415226216547/test/testwebapi:${{ steps.get-tag.outputs.short_ref }}
             me-west1-docker.pkg.dev/415226216547/test/testwebapi:latest
      - id: populate-configs
        uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        
        with:
          app_yaml_path: ".github/configs/app.yaml"

      - id: deploy
        name: Deploy Docker image to App Engine
        uses: google-github-actions/deploy-appengine@v1
        with:
          deliverables: '.github/configs/app.yaml'
